project:
  type: website
website:
  title: Lipidomics analysis
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: doc/learning.qmd
        text: "Report"
  page-footer:
    center:
      - text: "License: CC BY 4.0"
format:
  html:
    theme: vapor
knitr:
  opts_chunk:
    echo: false
editor:
  markdown:
    wrap: 72
    canonical: true
execute:
  freeze: true
