---
title: "Draft Quarto document"
author: "Your Name"
format: html
execute:
  echo: true
editor: 
  markdown: 
    wrap: 72
    canonical: true
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolites = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites")
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

```{r}
model_workflow <- create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
)
model_workflow
```

```{r}
fitted_model <- model_workflow %>%
  fit(lipidomics_wide)
fitted_model
```

```{r}
fitted_model %>%
  tidy_model_output()
```

```{r}
create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_lipid_ch_3_1)
) %>%
  fit(lipidomics_wide) %>%
  tidy_model_output()
```

### Running multiple models

```{r}
model_estimates <- lipidomics %>%
  split_by_metabolite() %>%
  map(generate_model_results) %>%
  list_rbind() %>%
  filter(str_detect(term, "metabolite_"))
model_estimates
```

```{r}

```
